version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6-node
    parallelism: 1
    steps:
      - checkout
      - run: gem install rails --no-rdoc --no-ri --update-sources
      - run: sudo apt-get install cmake curl
      - run: curl -fLSs https://circle.ci/cli | sudo bash
      - run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - run: bin/test

workflows:
  test:
    triggers: #use the triggers key to indicate a scheduled build
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
